


- id: 10.1139/facets-2022-0079
  image: https://quantmarineecolab.github.io/images/journal_covers/2023_Heard_etal_Facets.jpg
  extra-links:
    - type: pdf
      link: pdfs/2023_Heard_etal_Facets.pdf
  tags:
    - science communication
    - ecology





- id: 10.3389/fcosc.2022.987909
  image: https://quantmarineecolab.github.io/images/journal_covers/2021_Stoll_et_al_FrontSustFood.png
  extra-links:
    - type: pdf
      link: pdfs/2022_Saltzman_etal_FronConSci.pdf
  tags:
    - marine social science
    - sawfish
    - research methods






- id: 10.1007/s10980-022-01473-1
  image: https://quantmarineecolab.github.io/images/journal_covers/2022_Beasley_etal_LandEco.jpg
  extra-links:
    - type: pdf
      link: pdfs/2022_Beasley_etal_LandEco.pdf
  tags:
    - coffee
    - spatial ecology
    - disease





- id: 10.1016/j.marpol.2022.105054
  image: https://quantmarineecolab.github.io/images/journal_covers/2022_WardPaige_etal_MarPol.png
  extra-links:
    - type: pdf
      link: pdfs/2022_WardPaige_etal_MarPol.pdf
  tags:
    - COVID-19
    - novel data streams
    - socio-ecological




- id: 10.7717/peerj.13007
  image: https://quantmarineecolab.github.io/images/journal_covers/2022_White_etal_PeerJ.png
  extra-links:
    - type: pdf
      link: pdfs/2022_White_etal_PeerJ.pdf
    - type: blog 
      link: https://www.unh.edu/unhtoday/news/release/2022/03/21/unh-research-us-seafood-workers-increased-risk-covid-19-during-pandemic
  tags:
    - COVID-19
    - novel data streams
    - fisheries
    - seafood
    - worker safety



- id: 10.1111/csp2.611
  image: https://quantmarineecolab.github.io/images/journal_covers/2022_White_etal_ConSciPrac.jpg
  extra-links:
    - type: pdf
      link: pdfs/2022_White_etal_ConSciPrac.pdf
  tags:
    - conservation
    - monitoring
    - time series
    - marine mammals



- id: 10.1016/j.ocecoaman.2021.105925
  image: https://quantmarineecolab.github.io/images/journal_covers/2022_White_etal_OCM.jpg
  extra-links:
    - type: pdf
      link: pdfs/2022_White_etal_OCM.pdf
    - type: source
      link: https://github.com/eastonwhite/GFW-Madagascar
      text: Code
    - type: blog 
      link: https://quantmarineecolab.github.io/2021/12/15/madagascar-distant-fishing-paper.html
  tags:
    - Madagascar
    - novel data streams
    - fisheries
    - marine protected areas

    
    
    
    
- id: 10.1016/j.envsci.2021.06.007
  image: https://quantmarineecolab.github.io/images/journal_covers/2021_BakerMedard_etal_EnvSciPol.jpg
  extra-links:
    - type: pdf
      link: pdfs/2021_BakerMedard_etal_EnvSciPol.pdf
  tags:
    - socio-ecological
    - marine protected areas
    - Madagascar
    - conservation




- id: 10.1111/1365-2656.13560
  image: https://quantmarineecolab.github.io/images/journal_covers/2021_Osgood_et_al_AnimalEco.jpg
  extra-links:
    - type: pdf
      link: pdfs/2021_Osgood_et_al_AnimalEco.pdf
    - type: github
      link: baumlab/Osgood_etal_2021_JAE
  tags:
    - monitoring
    - sharks and rays
    - climate change




- id: 10.1016/j.ecoinf.2021.101336
  image: https://quantmarineecolab.github.io/images/journal_covers/2021_Bahlai_etal_EcoInformatics.jpg
  extra-links:
    - type: pdf
      link: pdfs/2021_Bahlai_etal_EcoInformatics.pdf
  tags:
    - monitoring
    - time series



- id: 10.3389/fsufs.2021.614368
  image: https://quantmarineecolab.github.io/images/journal_covers/2021_Stoll_et_al_FrontSustFood.png
  extra-links:
    - type: pdf
      link: pdfs/2021_Stoll_et_al_FrontSustFood.pdf
  tags:
    - COVID-19
    - seafood
    - fisheries




- id: 10.1111/oik.07770
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_White_etal_Oikos.png
  extra-links:
    - type: pdf
      link: pdfs/2020_White_etal_Oikos.pdf
    - type: source
      link: https://github.com/eastonwhite/MPA-disturbances
      text: Code
  tags:
    - monitoring
    - marine protected areas
    - fisheries
    - spatial ecology


- id: 10.1016/j.marpol.2020.104328
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_Froehlich_etal_MarPol.png
  extra-links:
    - type: pdf
      link: pdfs/2020_Froehlich_etal_MarPol.pdf
  tags:
    - COVID-19
    - seafood
    - fisheries




- id: 10.1111/faf.12525
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_White_etal_FishFisheries.png
  extra-links:
    - type: pdf
      link: pdfs/2020_White_etal_FishFisheries.pdf
    - type: github
      link: eastonwhite/COVID19_US_Fisheries
    - type: blog 
      link: https://quantmarineecolab.github.io/2020/11/15/seafood-and-covid-paper.html
  tags:
    - monitoring
    - COVID-19
    - seafood
    - fisheries



- id: 10.1016/j.ecolind.2020.107096
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_BruelWhite_EcoInd.png
  extra-links:
    - type: pdf
      link: pdfs/2020_BruelWhite_EcoInd.pdf
    - type: source
      link: https://github.com/rosalieb/temporal-sampling
      text: Code
  tags:
    - monitoring
    - population model
    - conservation



- id: 10.3389/fevo.2020.572979
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_WhiteBahlai_FronEcoEvo.png
  extra-links:
    - type: pdf
      link: pdfs/2020_WhiteBahlai_FronEcoEvo.pdf
  tags:
    - monitoring
    - population model
    - conservation




- id: 10.1371/journal.pone.0240648
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_WhiteHerbert-Dufresne_PLoSOne.png
  extra-links:
    - type: pdf
      link: pdfs/2020_WhiteHerbert-Dufresne_PLoSOne.pdf
    - type: source
      link: https://github.com/eastonwhite/COVID19_US_States
      text: Code
  tags:
    - COVID-19
    - public health




- id: 10.1016/j.ecocom.2020.100867
  image: https://quantmarineecolab.github.io/images/journal_covers/2020_WhiteHastings_EcoComp.png
  extra-links:
    - type: pdf
      link: pdfs/2020_WhiteHastings_EcoComp.pdf
  tags:
    - seasonality
    - population model



- id: 10.1073/pnas.1911440116
  image: https://quantmarineecolab.github.io/images/journal_covers/2019_White_etal_PNAS.png
  extra-links:
    - type: pdf
      link: pdfs/2019_White_etal_PNAS.pdf
    - type: source
      link: https://github.com/eastonwhite/species-management-variability
      text: Code
  tags:
    - beetles
    - monitoring
    - spatial ecology



- id: 10.1016/j.biocon.2019.07.011
  image: https://quantmarineecolab.github.io/images/journal_covers/2019_Rodriquez-Caro_BioCon.png
  extra-links:
    - type: pdf
      link: pdfs/2019_Rodriquez-Caro_BioCon.pdf
  tags:
    - monitoring
    - population model



- id: 10.1111/cobi.13371
  image: https://quantmarineecolab.github.io/images/journal_covers/2019_Fournier_etal_ConBio.png
  extra-links:
    - type: pdf
      link: pdfs/2019_Fournier_etal_ConBio.pdf
    - type: source
      link: https://github.com/aurielfournier/negative_population_trends
      text: Code
  tags:
    - monitoring
    - conservation



- id: 10.1093/biosci/biy144
  image: https://quantmarineecolab.github.io/images/journal_covers/2019_White_Bioscience.png
  extra-links:
    - type: pdf
      link: pdfs/2019_White_Bioscience.pdf
    - type: source
      link: https://github.com/eastonwhite/time-series-project
      text: Code
  tags:
    - monitoring
    - conservation



- id: 10.1002/ecy.2546
  image: https://quantmarineecolab.github.io/images/journal_covers/2018_WhiteSmith_Ecology.png
  extra-links:
    - type: pdf
      link: pdfs/2018_WhiteSmith_Ecology.pdf
    - type: source
      link: https://github.com/eastonwhite/BodiePikaMetapop
      text: Code
  tags:
    - pikas
    - spatial ecology
    - conservation

      

- id: 10.1111/cobi.12478
  image: https://quantmarineecolab.github.io/images/journal_covers/2015_White_etal_ConBio.png
  extra-links:
    - type: pdf
      link: pdfs/2015_White_etal_ConBio.pdf
    - type: source
      link: https://github.com/eastonwhite/Cocos_Models
      text: Code
  tags:
    - sharks and rays
    - marine protected areas
    - conservation



- id: 10.1186/1745-6150-9-23
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_White_etal_BiologyDirect.png
  extra-links:
    - type: pdf
      link: pdfs/2014_White_etal_BiologyDirect.pdf
    - type: source
      link: https://github.com/eastonwhite/LemonShark_Models
      text: Code
  tags:
    - sharks and rays
    - population model
    - conservation


- id: 10.3354/meps10966
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_Kessel_etal_MEPS.png
  extra-links:
    - type: pdf
      link: pdfs/2014_Kessel_etal_MEPS.pdf
  tags:
    - sharks and rays
    - seasonality




- id: 10.1016/j.marpol.2014.03.012
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_Robinson_etal_MarinePol.png
  extra-links:
    - type: pdf
      link: pdfs/2014_Robinson_etal_MarinePol.pdf
  tags:
    - conservation
    - biodiversity




- id: 10.1111/1365-2664.12177
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_GerberWhite_JAppEco.png
  extra-links:
    - type: pdf
      link: pdfs/2014_GerberWhite_JAppEco.pdf
  tags:
    - conservation
    - population model



- id: 10.1111/acv.12051
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_Senko_et_al_AnimConserv.png
  extra-links:
    - type: pdf
      link: pdfs/2014_Senko_et_al_AnimConserv.pdf
  tags:
    - conservation
    - fisheries
      

